apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tibero-pvc
  namespace: hyperauth
  labels:
    app: tibero
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  
